export enum SymboleEnum {
    EURUSD = "EURUSD",
    GBPUSD = "GBPUSD",
    USDJPY = "USDJPY",
    USDCAD = "USDCAD",
    USDCHF = "USDCHF",
    XAUUSD = "XAUUSD", // Gold
    XAGUSD = "XAGUSD", // Silver
    XPTUSD = "XPTUSD", // Platinum
    XPDUSD = "XPDUSD", // Palladium
    SPX500 = "SPX500", // S&P 500
    NAS100 = "NAS100", // Nasdaq 100
    DJ30 = "DJ30", // Dow Jones 30
    UK100 = "UK100", // FTSE 100
    GER30 = "GER30", // DAX 30
    FRA40 = "FRA40", // CAC 40
    JPN225 = "JPN225", // Nikkei 225
    AUS200 = "AUS200", // ASX 200
    HK50 = "HK50", // Hang Seng Index
    AUDUSD = "AUDUSD",
    NZDUSD = "NZDUSD",
    EURGBP = "EURGBP",
    EURJPY = "EURJPY",
    GBPJPY = "GBPJPY",
    EURCHF = "EURCHF",
    AUDJPY = "AUDJPY",
    GBPCHF = "GBPCHF",
    AUDNZD = "AUDNZD",
    AUDCAD = "AUDCAD",
    AUDCHF = "AUDCHF",
    CADJPY = "CADJPY",
    CHFJPY = "CHFJPY",
    EURCAD = "EURCAD",
    EURAUD = "EURAUD",
    EURNZD = "EURNZD",
    GBPAUD = "GBPAUD",
    GBPCAD = "GBPCAD",
    GBPNZD = "GBPNZD",
    NZDCAD = "NZDCAD",
    NZDCHF = "NZDCHF",
    NZDJPY = "NZDJPY",
    USDSGD = "USDSGD",
    USDHKD = "USDHKD",
    SGDJPY = "SGDJPY",
    USDMXN = "USDMXN",
    USDRUB = "USDRUB",
    USDZAR = "USDZAR",
    USDCNH = "USDCNH",
    USDDKK = "USDDKK",
    USDNOK = "USDNOK",
    USDSEK = "USDSEK",
    USDSAR = "USDSAR",
    USDCZK = "USDCZK",
    USDHUF = "USDHUF",
    USDPLN = "USDPLN",
    USDBRL = "USDBRL",
    USDCOP = "USDCOP",
}